version: '3.8'
services:
  authentication:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./auth:/app
    depends_on:
      - auth-db

  auth-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: quillpost_auth
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./auth/.dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  comments:
    build:
      context: ./comments
      dockerfile: Dockerfile
    ports:
      - 9000:8000
    volumes:
      - ./comments:/app
    depends_on:
      - comment-db

  comment-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: quillpost_comment
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./comments/.dbdata:/var/lib/mysql
    ports:
      - 33067:3306

  post:
    build:
      context: ./post/blog-post-service
      dockerfile: Dockerfile
    environment:
      POSTDB_HOST: post-db
      POSTDB_NAME: quillpost_post
      POSTDB_USERNAME: "root"
      POSTDB_PASSWORD: "1234"
    ports:
      - 8080:8080
    depends_on:
      - post-db

  post-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: quillpost_post
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./post/blog-post-service/.dbdata:/var/lib/mysql
    ports:
      - 3307:3306

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - authentication
      - post
      - comments
    develop:
      watch:
        - path: ./frontend
          target: /react-app
          action: sync
          ignore:
            - node_modules/
