apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi  
  selector:
    matchLabels:
      app: auth-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "quillpost_auth"

        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql  # MySQL data directory

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: auth-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: auth-db
spec:
  selector:
    app: auth-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  selector:
    matchLabels:
      app: authentication
  replicas: 1
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: pranavpras2001/quillpost_auth:latest
        ports:
          - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  selector:
    app: authentication
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
      nodePort: 30020
  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi  
  selector:
    matchLabels:
      app: comment-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-db
  template:
    metadata:
      labels:
        app: comment-db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "quillpost_comment"

        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql  # MySQL data directory

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: comment-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: comment-db
spec:
  selector:
    app: comment-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments
spec:
  selector:
    matchLabels:
      app: comments
  replicas: 1
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
      - name: comments
        image: pranavpras2001/quillpost_comments:latest
        ports:
          - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: comments
spec:
  selector:
    app: comments
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
      nodePort: 30025
  type: NodePort

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi  # Match the storage capacity with the PersistentVolume
  selector:
    matchLabels:
      app: post-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-db
  template:
    metadata:
      labels:
        app: post-db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "quillpost_post"

        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql  # MySQL data directory

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: post-db
spec:
  selector:
    app: post-db
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
spec:
  selector:
    matchLabels:
      app: post
  replicas: 1
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: pranavpras2001/quillpost_post:9.0
        ports:
          - containerPort: 8080
        env:
          - name: POSTDB_HOST
            value: post-db
          - name: POSTDB_NAME
            value: quillpost_post
          - name: POSTDB_USERNAME
            value: root
          - name: POSTDB_PASSWORD
            value: "1234"

---

apiVersion: v1
kind: Service
metadata:
  name: post
spec:
  selector:
    app: post
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30008
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: pranavpras2001/quillpost_frontend:3.0
        ports:
          - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
      nodePort: 30030
  type: NodePort
