apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi  # Match the storage capacity with the PersistentVolume
  selector:
    matchLabels:
      app: post-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-db
  template:
    metadata:
      labels:
        app: post-db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "quillpost_post"

        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql  # MySQL data directory

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: post-db
spec:
  selector:
    app: post-db
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
spec:
  selector:
    matchLabels:
      app: post
  replicas: 1
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: pranavpras2001/quillpost_post:8.0
        ports:
          - containerPort: 8080
        env:
          - name: POSTDB_HOST
            value: post-db
          - name: POSTDB_NAME
            value: quillpost_post
          - name: POSTDB_USERNAME
            value: root
          - name: POSTDB_PASSWORD
            value: "1234"

---

apiVersion: v1
kind: Service
metadata:
  name: post
spec:
  selector:
    app: post
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30008
  type: NodePort